### ISSUE TITLE
PR #2

### ISSUE THREAD

**Issue by mateatslc** [everdimension/angular-svg-base-fix#3]
Any comment on #2?

**Comment by mateatslc** [comment]
thanks for accepting!

**Comment by everdimension** [comment]
Thanks for the pr!

**Comment by mateatslc** [comment]
ohh, would you mind publishing this change to npm please

**Comment by everdimension** [comment]
https://github.com/everdimension/angular-svg-base-fix/releases/tag/v1.0.1
It's on npm ;)

**Comment by mateatslc** [comment]
awesome, thanks :)
